version: "3"
services:
  wwww:
    build: ./php
    ports:
      - "90:80"
      - "5180:5180"
    volumes:
      - "./app:/var/www/html"
      - "./logs/apache2:/var/log/apache2"
      - "./apache/default.conf:/etc/apache2/sites-available/000-default.conf"

  db:
    image: mariadb:10.5.12
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cleanedcontent
    ports:
      - 3416:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 91:80
    environment:
      MEMORY_LIMIT: 256M
      UPLOAD_LIMIT: 100M

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1090:1080"
      - "1030:1025"